version: 2
updates:
- package-ecosystem: npm
  directory: "/front-end"
  schedule:
    interval: monthly
    time: "07:07"
    timezone: US/Central
  open-pull-requests-limit: 10
  assignees:
  - mreishus
  ignore:
  - dependency-name: flow-bin
    versions:
    - 0.141.0
    - 0.143.1
  - dependency-name: react-scripts
    versions:
    - 4.0.1
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
- package-ecosystem: npm
  directory: "/word-vector-service"
  schedule:
    interval: monthly
    time: "07:07"
    timezone: US/Central
  open-pull-requests-limit: 10
  assignees:
  - mreishus
  ignore:
  - dependency-name: eslint
    versions:
    - 7.16.0
    - 7.19.0
  - dependency-name: nodemon
    versions:
    - 2.0.6
  - dependency-name: lodash
    versions:
    - 4.17.20
